### ISSUE TITLE
High CPU load in long files

### ISSUE THREAD

**Issue by ANK-dev** [kshetline/ligatures-limited#7]
* Extension version: `1.1.0`
* VS Code version: `1.45.1`
* OS version: `Microsoft Windows [Version 10.0.19041.264]`

It appears that when editing long files (>1000 lines) the extension tends to become unresponsive and use high amounts of CPU time. I'm attaching some CPU profiles for futher analysis.

![image](https://user-images.githubusercontent.com/40664661/83423871-f88af400-a401-11ea-93e3-ab03a1a3bcf0.png)

CPU profiles:
[ligatures-limited-cpu-profile.zip](https://github.com/kshetline/ligatures-limited/files/4712066/ligatures-limited-cpu-profile.zip)

**Comment by kshetline** [comment]
Oops! Looks like I made what was supposed to be a temporary change at one point for testing something, and forgot to put the code back the right way.

`if (processMillis() > started + 50_000_000)`

That line is supposed to make sure big files are processed in small chunks, but now it's letting more than 13 hours go by before yielding!

**Comment by kshetline** [comment]
This looks like it will take a little longer to fix than I thought. Fixing the above problem would only be a partial fix, because oddly enough, and for reasons I haven't figured out yet, it's not just the total size of the file that matters, but as the file gets larger, each individual line is taking longer to process. There shouldn't be anything n^2, or even n log n, about the way this works, so why it slows down the way it does will require some investigation.

**Comment by kanlukasz** [comment]
I can confirm I had same problem

**Comment by kshetline** [comment]
I've pushed a fix for this problem. It's still possible that, when editing a VERY large file, an occasional warning will be issued like this:

```text
[2020-06-03 16:58:47.331] [renderer1] [warning] UNRESPONSIVE extension host,
'kshetline.ligatures-limited' took 99% of 5408.239ms, saved PROFILE here: '/var/folders/
68/jf210np51m71xfvc4n6x_dhr0000gn/T/exthost-0710c7.cpuprofile' [{"id":"gc","total":50059,"percentage":1},{"id":"kshetline.ligatures-limited",
"total":5356839,"percentage":99},{"id":"self","total":1270,"percentage":0}]
```
...but this seems harmless, and the editor remains responsive when this happens.

**Comment by ANK-dev** [comment]
Unfortunately, the extension is still lagging **hard** for me when writing in my >1200 lines markdown file, borderline unusable. Editing the same file while using CoenraadS' `vscode-Disable-Ligatures` works effortlessly.

**Comment by kshetline** [comment]
Are you sure you reloaded VSCode after the update to 1.2.0?

**Comment by ANK-dev** [comment]
Yep. Kept disabling `ligatures-limited`, reloading, enabling `vscode-Disable-Ligatues` and vice-versa (for comparison), and every time `ligatures-limited` kept choking and freezing (up to several seconds), and `vscode-Disable-Ligatues` worked flawlessly.

**Comment by kshetline** [comment]
Is this file you've having trouble with something you can send me? Or if that particular file is private, is there an open-source file you can point me to that shows the same problem?

I definitely found some issues that needed fixing, and fixed those problems, but it seems there's more that's going on that I haven't yet run into myself. I experimented with a plain text file that was nearly 20,000 lines long, with lots of ligatures in it, and the worst I saw at that size was a bit of lag in the enabling and disabling of ligatures, while I was still able to type easily, with nothing choking up.

It's not too surprising that vscode-Disable-Ligatues doesn't have similar problems, because it works with files purely as straight-forward text, and doesn't have to do any language parsing to figure out which ligatures are shown or not.

**Comment by kshetline** [comment]
I just made a large Markdown file by taking a sample file I found online, and repeatedly pasting the same contents over and over until it was around 10,000 lines long. I works beautifully for me.
[sample2.md.zip](https://github.com/kshetline/ligatures-limited/files/4727581/sample2.md.zip)

**Comment by kanlukasz** [comment]
I tested the file `sample2.md.zip` after upgrading to version` 1.2.0` and it works fine for me

@ANK-dev - send the file and I will also test it

@kshetline as you wrote _`vscode-Disable-Ligatues doesn't have similar problems, because it works with files purely as straight-forward text, and doesn't have to do any language parsing to figure out which ligatures are shown or not`_ i have a question now. Can we disable parsing if someone using this plugin only for highlighted ligatures to see classic font?

**Comment by ANK-dev** [comment]
Bingo! I seem to have found the culprits, and the way it works is quite bizarre.

I started by disabling all my extensions, and then, one-by-one, enabling them to find which one was causing the lag. These are the results:

* No extensions enabled → editing works perfectly, no lag, no freezes.
* Just `ligatures-limited` enabled → editing works perfectly, lag while processing some ligatures but it doesn't freeze user input—I can keep typing while it catches up to the cursor.
* `ligatures-limited` and `adammaras.overtype` enabled → extreme lag while typing, but not while backspacing, I'm always 3 words ahead of where the cursor appears. It seems this issue isn't isolated, as on the extension's GitHub issues page other people mention the same issue. This extension hasn't been updated in over 4 years, so this might be contributing to some problems.
* `ligatures-limited` and `yzhang.markdown-all-in-one` enabled → typing works; backspacing however, results in extreme lag.
* `ligatures-limited`, `yzhang.markdown-all-in-one`, and `adammaras.overtype` → lagging and freezes all around. Typing lags, and backspacing lags.

@kshetline: The only issue left is as you mentioned: when editing large files, some warnings appear in the console, and the rendering of ligatures appears to lag behind the cursor, but the editor remains fully responsive during the entire time. I don't know if this is viable to fix, but it seems like everything is working **much** better than before! Thanks for your attention.

**Comment by kshetline** [comment]
I've just installed both of these extensions, Overtype and Markdown All in One, and I'm definitely seeing the same problems you are. Whether I'll be able to fix those problems, that's another matter, but I'll give it a try. AFAIK, I'm not doing anything wrong with my code that should create conflicts, but I'll have to investigate further.

It would certainly be nice to be able to comfortably use these various tools together.

**Comment by kshetline** [comment]
I've managed to get Ligatures Limited working along with both Overtype and Markdown All in One, at least for me, and working faster in general. Please let me know if the latest version works better for you.

**Comment by ANK-dev** [comment]
Thanks! It all seems to be working correctly. Typing is very fast and responsive. Since I can't seem to trigger any slowdowns anymore I consider this issue closed.
